<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => 'Администратор',
    'A user with such data is not registered on the site!' => 'Пользователь с такими данными не зарегистрирован на сайте!',
    'Account deletion date' => 'Дата удаления аккаунта',
    'address not set' => 'адрес не заполнен',
    'activ' => 'активность',
    'Activity' => 'Активность',
    'All' => 'Все',
    'Basic information' => 'Основная информация',
    'block' => 'блок',
    'blocked until' => 'заблокирован до',
    'Blocking' => 'Блокировка',
    'Child' => 'Потомок',
    'City' => 'Город',
    'Client Authentication Code' => 'Код аутентификации клиента',
    'Site information' => 'Данные для сайта',
    'Country' => 'Страна',
    'Create a new user' => 'Создать нового пользователя',
    'Data update date' => 'Дата обновления данных',
    'data was not updated' => 'данные не обновлялись',
    'Date added' => 'Дата добавления',
    'Date created role' => 'Дата создания роли',
    'Date of registration in the system' => 'Дата регистрации в системе',
    'Date of renewal' => 'Дата обновления',
    'Date of role assignment?' => 'Дата задания роли ?',
    'Do not get out of the system' => 'Не выходить из систамы',
    'E-mail or password is entered incorrectly!' => 'E-mail или пароль введен не верно!',
    'encrypted and hidden' => 'зашифрован и скрыт',
    'F.L.M.' => 'Ф.И.О.',
    'Fem.' => 'Жен.',
    'First Name' => 'Имя',
    'Gender' => 'Пол',
    'Group' => 'Группа',
    'Home phone' => 'Домашний телефон',
    'House number/apartment' => 'Номер дома/квартира',
    'Index' => 'Индекс',
    'Key description' => 'Ключевые описания',
    'Last Activity' => 'Последняя активность',
    'Lock Date' => 'Дата блокировки',
    'Login' => 'Логин',
    'Login or E-mail' => 'Логин или E-mail',
    'Middle name' => 'Отчество',
    'Mobile' => 'Мобильный',
    'Moderator' => 'Модератор',
    'Name' => 'Наименование',
    'New password' => 'Новый пароль',
    'New password again' => 'Новый пароль ещё раз',
    'New user created' => 'Создан новый пользователь',
    'no expiration date' => 'бессрочно',
    'no last name' => 'фамилия не задана',
    'no name specified' => 'имя не задано',
    'not set' => 'не установлен',
    'not specified' => 'не задан',
    'Old password' => 'Старый пароль',
    'Parent' => 'Родитель',
    'Password' => 'Пароль',
    'Password reset code' => 'Код сброса пароля',
    'patronymic is not set' => 'отчество не задано',
    'Profilfoto' => 'Аватар',
    'Region' => 'Регион',
    'Repeat password' => 'Повтор пароля',
    'Role data' => 'Данные роли',
    'Role Name' => 'Наименование роли',
    'select a date and time' => 'выбирите дату и время',
    'select group' => 'выберите группу',
    'Simple user' => 'Простой пользователь',
    'Street (lane)' => 'Улица (переулок)',
    'Surname' => 'Фамилия',
    'System information' => 'Системная информация',
    'The date the role was updated' => 'Дата обновления роли',
    'The new password should not be the same as the old password!' => 'Новый пароль не должен быть таким же, как и старый пароль!',
    'The title of the role?' => 'Название роли ?',
    'This user does not exist.' => 'Такого пользователя не существует.',
    'Type' => 'Тип',
    'Update user details' => 'Обновить данные пользователя',
    'User' => 'Пользователь',
    'User agreement' => 'Пользовательское соглашение',
    'User data updated successfully!' => 'Данные о пользователе успешно обновлены!',
    'User ID' => 'ID пользователя',
    'user not authorized on the site' => 'пользователь не авторизовывался на сайте',
    'Users' => 'Пользователи',
    'User deleted successfully!' => 'Пользователь успешно удалён',
    'Verify code' => 'Проверочный код',
    'Work phone' => 'Рабочий телефон',
];
